#ifndef HARDWARE_H
#define	HARDWARE_H

#define DEVTYPE_MUNIA_ORIGINAL 0x00
#define DEVTYPE_MUNIA_NGC 0x01
#define DEVTYPE_MUNIA_N64 0x02
#define DEVTYPE_MUNIA_SNES 0x03

#define HW_REVISION 0x00
#define MUNIA_DEVICETYPE DEVTYPE_MUNIA_N64

#define _XTAL_FREQ 48000000

#define N64_DAT PORTCbits.RC1
#define N64_DAT_TRIS TRISCbits.TRISC1

#define SWITCH2 LATBbits.LATB2 // for n64

#endif	/* HARDWARE_H */
