#ifndef HARDWARE_H
#define	HARDWARE_H

#define DEVTYPE_MUNIA_ORIGINAL 0x00
#define DEVTYPE_MUNIA_NGC 0x01
#define DEVTYPE_MUNIA_N64 0x02
#define DEVTYPE_MUNIA_SNES 0x03

#define HW_REVISION 0x00
#define MUNIA_DEVICETYPE DEVTYPE_MUNIA_SNES

#define _XTAL_FREQ 48000000

#define SNES_DAT PORTCbits.RC2
#define SNES_LATCH PORTCbits.RC7
#define SNES_CLK PORTAbits.RA7

#define SNES_DAT_TRIS TRISCbits.TRISC2
#define SNES_LATCH_TRIS TRISCbits.TRISC7
#define SNES_CLK_TRIS TRISAbits.TRISA7
#define N64_DAT_TRIS TRISCbits.TRISC1
#define NGC_DAT_TRIS TRISCbits.TRISC0

#define LED_SNES_GREEN LATAbits.LATA5
#define LED_SNES_ORANGE LATCbits.LATC6
#define LED_GC_GREEN LATBbits.LATB6
#define LED_GC_ORANGE LATBbits.LATB7

#define SWITCH3 LATBbits.LATB0 // for snes

#endif	/* HARDWARE_H */
