#ifndef HARDWARE_H
#define	HARDWARE_H

#define DEVTYPE_MUNIA_ORIGINAL 0x00
#define DEVTYPE_MUNIA_NGC 0x01
#define DEVTYPE_MUNIA_N64 0x02
#define DEVTYPE_MUNIA_SNES 0x03

#define HW_REVISION 0x00
#define MUNIA_DEVICETYPE DEVTYPE_MUNIA_NGC

#define _XTAL_FREQ 48000000

#define LED_GC_GREEN LATBbits.LATB6
#define LED_GC_ORANGE LATBbits.LATB7

#define SWITCH1 LATBbits.LATB2 // for ngc

#endif	/* HARDWARE_H */
