# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('release_notes', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to=b'versions')),
            ],
        ),
    ]
